In [27]:
#Kronocker product of two matrices
import numpy as np
mat1=[[1,2],
        [3,4]]

mat2=[[0,5],
        [3,2]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)


result = np.zeros((mat1_shape[0]*mat2_shape[0], mat1_shape[1]*mat2_shape[1]))

for i in range(mat1_shape[0]):
    for j in range(mat1_shape[1]):
        result[i*mat2_shape[0]:(i+1)*mat2_shape[0], j*mat2_shape[1]:(j+1)*mat2_shape[1]] = mat1_np[i,j] * mat2_np

print("Resulting matrix:")
print(result)

Resulting matrix:
[[ 0.  5.  0. 10.]
 [ 3.  2.  6.  4.]
 [ 0. 15.  0. 20.]
 [ 9.  6. 12.  8.]]


In [20]:
#Kronocker product of two matrices

mat1=[[1,2],
        [3,4]]

mat2=[[0,5],
        [3,2]] 

rowa = len(mat1)
cola = len(mat1[0])
rowb = len(mat2)
colb = len(mat2[0])

result = [[0 for i in range(cola*colb)] for j in range(rowa*rowb)]

for i in range(rowa):
        for j in range(rowb):
                for k in range(cola):
                        for l in range(colb):
                                result[i*rowb+j][k*colb+l] = mat1[i][k] * mat2[j][l]


print("Resulting matrix:")
for row in result:
        for ele in row:
                print(ele, end = " ")
        print()       
    
        

Resulting matrix:
0 5 0 10 
3 2 6 4 
0 15 0 20 
9 6 12 8 


In [4]:
import numpy as np
mat1=[[1,2],
        [3,4],
        [1,0]]

mat2=[[0,5,2],
        [6,7,3]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)


result = np.zeros((mat1_shape[0]*mat2_shape[0], mat1_shape[1]*mat2_shape[1]))

for i in range(mat1_shape[0]):
    for j in range(mat1_shape[1]):
        result[i*mat2_shape[0]:(i+1)*mat2_shape[0], j*mat2_shape[1]:(j+1)*mat2_shape[1]] = mat1_np[i,j] * mat2_np

print("Resulting matrix:")
print(result)

Resulting matrix:
[[ 0.  5.  2.  0. 10.  4.]
 [ 6.  7.  3. 12. 14.  6.]
 [ 0. 15.  6.  0. 20.  8.]
 [18. 21.  9. 24. 28. 12.]
 [ 0.  5.  2.  0.  0.  0.]
 [ 6.  7.  3.  0.  0.  0.]]


In [41]:
#MAGIC SQUARE
import numpy as np

def is_magic_square(matrix):

    matrix = np.array(matrix)
    
    n = int(input("Enter the n: "))
    expected_sum = (n * (n**2 + 1)) // 2

    if matrix.shape != (n, n):
        return False
    
    
    # Check rows
    if not all(np.sum(matrix, axis=1) == expected_sum):
        return False
    
    # Check columns
    if not all(np.sum(matrix, axis=0) == expected_sum):
        return False
    
    # Check main diagonal
    if not np.trace(matrix) == expected_sum:
        return False
    
    # Check secondary diagonal
    if not np.sum(np.diag(np.fliplr(matrix))) == expected_sum:
        return False
    
    return True

sample_matrix = [[2,7,6],[9,5,1],[4,3,8]]
if is_magic_square(sample_matrix):
    print("Yes")
else:
    print("No")

Yes


In [1]:
#MAGIC SQUARE WITHOUT BUILT-IN FUNCTION

def magic_square(matrix):
    n = len(matrix)
    magic_sum = n*(n**2 + 1)//2
    sum_rows = [0]*n
    sum_cols = [0]*n
    sum_diag = 0
    sum_diag2 = 0

    for i in range(n):
        for j in range(n):
            sum_rows[i] += matrix[i][j]
            sum_cols[j] += matrix[i][j]
            if i == j:
                sum_diag += matrix[i][j]
            if i + j == n - 1:
                sum_diag2 += matrix[i][j]

    if sum_diag != magic_sum or sum_diag2 != magic_sum:
        return False

    for i in range(n):
        if sum_rows[i] != magic_sum or sum_cols[i] != magic_sum:
            return False

    return True
    

matrix = [[2,7,6],[9,5,1],[4,3,8]]

if magic_square(matrix):
    print("Yes")
else:
    print("No")

Yes


In [42]:
#MATRIX ADDITION AND MULTIPLICATION

import numpy as np
mat1=[[1,2],
        [3,4]]

mat2=[[0,5],
        [3,2]]  

mat1_shape = np.shape(mat1)
mat2_shape = np.shape(mat2)

mat1_np = np.array(mat1)
mat2_np = np.array(mat2)

# Matrix Multiplication
print("Matrix Multiplication:")
multiplication_result = np.dot(mat1_np, mat2_np)
print(multiplication_result)

# Matrix Addition
print("\nMatrix Addition:")
addition_result = mat1_np + mat2_np
print(addition_result)



Matrix Multiplication:
[[ 6  9]
 [12 23]]

Matrix Addition:
[[1 7]
 [6 6]]


In [44]:
#MATRIX ROTATIONS

import numpy as np

array = np.array([2000, 500, 100, 50, 10, 5, 2, 1])

rotations = int(input("Enter the number of rotations: "))

# Perform left rotation
left_rotated = np.roll(array, -rotations)

# Perform right rotation
right_rotated = np.roll(array, rotations)

print("\nOriginal array:", array)
print("Left rotated array:", left_rotated)
print("Right rotated array:", right_rotated)


Original array: [2000  500  100   50   10    5    2    1]
Left rotated array: [ 100   50   10    5    2    1 2000  500]
Right rotated array: [   2    1 2000  500  100   50   10    5]
