In [24]:
import numpy as np

my_arr = np.arange(10)
print(my_arr)
print(type(my_arr))

my_arr = np.arange(2,8)
print(my_arr)

my_arr = np.arange(1,10,2)
print(my_arr)

my_arr = np.arange(1,10,0.5)
print(my_arr)


print()
print()
print()


from_list = np.array([1,2,3,4,5])
print(from_list)
print(type(from_list))
print(type(from_list[0])) # takes lot of space

from_list = np.array([1,2,3,4,5],dtype=np.int8)
print(from_list)
print(type(from_list))
print(type(from_list[0])) # takes less space
print(from_list.dtype)
print(from_list.itemsize)
print(from_list.size)
print(from_list.shape)



print()



[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[2 3 4 5 6 7]
[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]



[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.int8'>
int8
1
5
(5,)



In [29]:
#2D arrays

from_list = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int8)
print(from_list)
print(from_list.shape)

print()
array_2d = np.array((np.arange(1,6),np.arange(6,11),np.arange(11,16)))
print(array_2d)
print(array_2d.shape)
 
array_2d = array_2d.reshape(5,3)
print(array_2d)

array_2d = array_2d.reshape(15)
print(array_2d)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [52]:
#empty array
zero_array = np.zeros((3,3))
print(zero_array)

one_array = np.ones((3,3))
print(one_array)

eye_array = np.eye(3)
print(eye_array)

eye_array = np.eye(3,k=1) #k is the diagonal offset, k=-1 below diagonal , k = 1 above diagonal
print(eye_array)

empty_array = np.empty((3,3))#don't use it , it returns random values
print(empty_array)


test_array = np.eye(4)
print(test_array)
test_array[test_array == 0] = 2
print(test_array) 
test_array[test_array < 2 ] =4
print(test_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 2. 2. 2.]
 [2. 1. 2. 2.]
 [2. 2. 1. 2.]
 [2. 2. 2. 1.]]
[[4. 2. 2. 2.]
 [2. 4. 2. 2.]
 [2. 2. 4. 2.]
 [2. 2. 2. 4.]]


In [62]:
array = np.array(np.arange(1,10)).reshape(3,3)
array[0] = 2
print(array)
array[1] = 2
print(array)
array[2] = 2
print(array)
array = np.array(np.arange(1,10)).reshape(3,3)
array[:2] = 2
print(array)


[[2 2 2]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[2 2 2]
 [2 2 2]
 [7 8 9]]


In [67]:
array = np.array(np.arange(1,10)).reshape(3,3)
print(array)
array[:,0] = 4
print(array)


sorted_Array = np.sort(array) # sorting by row
print(sorted_Array)

#sorting by column
sorted_Array = np.sort(sorted_Array,axis=0,kind="mergesort") #axis = 0 column , axis = 1 row
print(sorted_Array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 2 3]
 [4 5 6]
 [4 8 9]]
[[2 3 4]
 [4 5 6]
 [4 8 9]]
[[2 3 4]
 [4 5 6]
 [4 8 9]]


In [70]:
#copy arrays
array = np.array(np.arange(1,10)).reshape(3,3)

my_view = array.view() # view directly modifies the original array, only the values is changes
                        #if the shape is changes it will not change the original array 
print(my_view)
my_copy = array.copy()
print(my_copy)

my_view[:] = 4
print()
print(my_view)
print(my_copy)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
